system("rm -rf _next")
system("mkdir _next")
build_id = File.read('.next/BUILD_ID')
system("mkdir _next/#{build_id}")
system("mkdir _next/#{build_id}/page")
system("cp -r ./.next/bundles/pages/* ./_next/#{build_id}/page/")
system("mkdir _next/static")
system("cp -r ./.next/static/* ./_next/static/")
system("mkdir _next/webpack")
system("mkdir _next/webpack/chunks")
system("cp -r ./.next/chunks/* ./_next/webpack/chunks/")
